# Generated by Django 4.2.13 on 2024-05-31 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myparking', '0011_parkingspot_date_of_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newscrat', models.CharField(max_length=100, verbose_name='Краткая')),
                ('news', models.CharField(max_length=300, verbose_name='Полная')),
            ],
        ),
    ]
