# Generated by Django 4.2.13 on 2024-05-31 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myparking', '0012_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='newscrat',
        ),
        migrations.AddField(
            model_name='news',
            name='news_label',
            field=models.CharField(default='article title', max_length=30),
        ),
        migrations.AddField(
            model_name='news',
            name='newsimg',
            field=models.ImageField(default='asd', upload_to='static', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news',
            field=models.CharField(max_length=100, verbose_name='Краткая'),
        ),
    ]
