# Generated by Django 4.2.13 on 2024-05-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myparking', '0013_remove_news_newscrat_news_news_label_news_newsimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_long',
            field=models.CharField(default='content', max_length=300, verbose_name='Полная'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news',
            field=models.CharField(default='content', max_length=100, verbose_name='Краткая'),
        ),
    ]
